//dropdown items
export const items = [
  {
    title: "Most Recent",
    option: ["Highest Hourly Pay", "Highest Budget"],
  },
  {
    title: "Date Posted",
    option: ["Today", "1-3 Days", "1-7 Days"],
  },
  {
    title: "Job Type",
    option: ["Hourly", "Fixed Price"],
  },
  {
    title: "Category",
    option: [
      "AR/VR Development",
      "Automation Testing",
      "Back-End Development",
      "CMS Development",
      "Coding Tutoring",
      "Database Development",
      "Desktop Software Development",
      "Ecommerce Development",
      "Emerging Tech",
      "Firmware Development",
      "Front-End Development",
      "Full Stack Development",
      "Game Development",
      "Manual Testing",
      "Mobile App Development",
      "Mobile Design",
      "Mobile Game Development",
      "Product Management",
      "Prototyping",
      "Scripting & Automation",
      "Scrum Master",
      "User Research",
      "UX/UI Design",
      "Web Design"
    ],
  },
  {
    title: "Skills",
    option: [
      "Adobe Photoshop",
      "Amazon Web Services",
      "Android Development",
      "Angular",
      "AngularJS",
      "Apache HTTP Server",
      "API",
      "Bootstrap",
      "C",
      "C++",
      "ClojureScript",
      "CoffeeScript",
      "CSS",
      "CSS3",
      "C Sharp",
      "Django",
      "ECMAScript",
      "Elm",
      "Figma",
      "Flask",
      "Flutter",
      "Google Analytics",
      "Graphic Design",
      "GraphQL",
      "GO",
      "HAML",
      "Haxe",
      "HTML",
      "HTML5",
      "iOS Development",
      "Java",
      "JavaScript",
      "JSON",
      "jQuery",
      "Kubernetes",
      "Less",
      "Microsoft VBScript",
      "MySQL",
      "Next.js",
      "Node.js",
      "NoSQL",
      "PHP",
      "PostgreSQL",
      "Python",
      "React",
      "React Native",
      "Redis",
      "Redux",
      "RESTful",
      "Ruby",
      "Sass",
      "SCSS",
      "Shopify",
      "Sketch",
      "SQL",
      "Tailwind CSS",
      "TypeScript",
      "UX/UI",
      "Vue.js",
      "Web Design",
      "WordPress",
      "XHTML",
      "XML"
    ],
  },
  {
    title: "Salary",
    option: [""],
  },
  {
    title: "Location",
    option: [
      "United States",
      "International"
    ],
  },
];
